// Produits de fallback en cas d'échec de l'API
// Avec vrais liens Amazon comme dans la base de données
export const fallbackProducts = [
  {
    _id: "fallback-1",
    productId: "casque-anti-bruit",
    title: "Casque Anti-Bruit pour Enfants",
    description: "Casque de protection auditive confortable, idéal pour réduire les stimuli sonores et favoriser la concentration dans les environnements bruyants.",
    price: 34.99,
    imageUrl: "/assets/shop/casque-anti-bruit.webp",
    link: "https://www.amazon.fr/dp/B07QRSTUVW",
    category: "Protection",
  },
  {
    _id: "fallback-2",
    productId: "balle-sensorielle",
    title: "Balles Sensorielles Texturées - Set de 6",
    description: "Set de 6 balles aux textures variées pour stimuler le toucher et développer la motricité fine. Parfait pour les activités sensorielles.",
    price: 24.99,
    imageUrl: "/assets/shop/balle-sensorielle-lumineuse.webp",
    link: "https://www.amazon.fr/dp/B08XYZABC1",
    category: "Sensoriel",
  },
  {
    _id: "fallback-3",
    productId: "timer-visuel",
    title: "Time Timer Visuel - Gestion du Temps",
    description: "Timer visuel magnétique pour aider à comprendre le passage du temps. Parfait pour structurer les activités et les transitions.",
    price: 39.99,
    imageUrl: "/assets/shop/timer-visuel.webp",
    link: "https://www.amazon.fr/dp/B07VWXYZAB",
    category: "Organisation",
  },
  {
    _id: "fallback-4",
    productId: "tapis-sensoriel",
    title: "Tapis Sensoriel d'Activités",
    description: "Grand tapis avec différentes zones texturées pour stimuler le sens tactile et développer l'exploration sensorielle.",
    price: 54.99,
    imageUrl: "/assets/shop/tapis-sensoriel.webp",
    link: "https://www.amazon.fr/dp/B09QRSTUVW",
    category: "Sensoriel",
  },
  {
    _id: "fallback-5",
    productId: "sequenceur-visuel",
    title: "Séquenceur Visuel Magnétique",
    description: "Tableau magnétique avec pictogrammes pour créer des routines visuelles et faciliter l'organisation quotidienne.",
    price: 29.99,
    imageUrl: "/assets/shop/classeur-pecs.webp",
    link: "https://www.amazon.fr/dp/B08JKLMNOP",
    category: "Organisation",
  },
  {
    _id: "fallback-6",
    productId: "coussin-leste",
    title: "Coussin Lesté Apaisant 2kg",
    description: "Coussin lesté de haute qualité procurant une sensation de pression profonde pour calmer l'anxiété et favoriser la relaxation.",
    price: 44.99,
    imageUrl: "/assets/shop/chaise-bascule.webp",
    link: "https://www.amazon.fr/dp/B08KLMNSTU",
    category: "Sensoriel",
  },
];

